#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
xsetroot -solid '#30404F'
xsetroot -cursor_name left_ptr
urxvtd -q -f -o
#xmodmap .Xmodmap
hhp &
exec ssh-agent xmonad
